## **1. Creating Arrays**

In [1]:
import numpy as np

In [11]:
# 1D
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
# 2D
Two_D =np.array([[1,2,3],[4,5,6]])
Two_D

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Array of zeros
zeros =np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Array of ones
ones =np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Array with a range of value
range_arrays = np.arange(0,10,2)
range_arrays

array([0, 2, 4, 6, 8])

In [15]:
 # Array with evenly spaced values
 linspace_array =np.linspace(0,2,6)
 linspace_array

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

## **2. Array Attributes**

In [17]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
a


array([1, 2, 3])

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [22]:
print(a.ndim)
print(b.ndim)   # Dimension

1
2


In [24]:
print(a.dtype)
print(b.dtype)

int64
int64


## **3. Basic Operations**

In [25]:
x = np.array([1,2,3]) 
y = np.array([4,5,6])

In [26]:
# Element-wise addirion
print(x+y)

[5 7 9]


In [27]:
# Element-wise additon
print( x*y )

[ 4 10 18]


In [28]:
# Universal function
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


## **4. Indexing and Slicing**

In [29]:
arr = np.array([[1,2,3],[4,5,6]])

In [30]:
# Accessing element 
print(arr[0,2]) # Output : 3

3


In [31]:
# Slicing
print(arr[:, 1])

[2 5]


In [32]:
print(arr[:,2])

[3 6]


In [34]:
# Fancy indexing
a = np.array([10,20,30,40,50])
print(a[[0,2]])

[10 30]


In [35]:
# Nagetive indexing
print(a[-1])

50


## **5. Boolean Masking**

In [36]:
mask = arr > 3
print(arr[mask])

[4 5 6]


In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

##  **6. Reshapping Array**

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
reshaped = arr.reshape((3,2))
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

## **7. Stacking Array**

In [40]:
a = np.array([1,2])
b = np.array([3,4])

In [41]:
# Vertical stack
print(np.vstack((a, b)))

[[1 2]
 [3 4]]


In [42]:
# Horizontal stack
print(np.hstack((a, b)))

[1 2 3 4]


## **8. Splitting Array**

In [43]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.hsplit(x, 3)    # Split into 3 columns
np.vsplit(x, 2)    # Split into 2 rows

[array([[1, 2, 3]]), array([[4, 5, 6]])]

## **9. Broadcasting**

In [44]:
a = np.array([1,2,3,4])
b = np.array([[4],[5],[6]])
print(a, "next")
print(b)

[1 2 3 4] next
[[4]
 [5]
 [6]]


In [45]:
print(a + b)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


## **10. Linear Algebra Operations**

In [46]:

from numpy.linalg import inv, eig, svd

In [47]:
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [48]:
# inverse
print(inv(matrix))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [49]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(matrix)

In [50]:
print(eigenvalues)

[-0.37228132  5.37228132]


In [51]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [52]:
# Singular Value Decomposition
U, S, V = svd(matrix)

In [53]:
print(U)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]


In [54]:
print(S)

[5.4649857  0.36596619]


In [55]:
print(V)

[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [56]:
# Matrix Multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = a @ b
c

array([[19, 22],
       [43, 50]])

In [57]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [58]:
# Matrix Inverse & Determinant
from numpy.linalg import inv, det
inv_a = inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
det_a = det(a)
det_a

np.float64(-2.0000000000000004)

In [60]:
# Solve Linear Systems
from numpy.linalg import solve
x = solve(a, np.array([1, 0]))

In [61]:
x

array([-2. ,  1.5])

## **11. Random Number Generation**

In [62]:
# Random floats in [0.0, 1.0]
random_floats = np.random.rand(3,2)

In [65]:
random_floats


array([[0.86132811, 0.6275928 ],
       [0.58299166, 0.02265547],
       [0.85488157, 0.15633149]])

In [68]:
# Random integers b/w 0 and 20
random_integers = np.random.randint(0, 20, size= (3,2))
random_integers


array([[7, 1],
       [9, 8],
       [2, 4]], dtype=int32)

In [69]:
# Generate Random Values
import numpy as np

In [70]:
np.random.rand(2, 3)     # Uniform [0, 1)

array([[0.03780252, 0.70178417, 0.46907476],
       [0.91302009, 0.47758579, 0.18688143]])

In [71]:
np.random.randint(1, 10, size=(2, 3))  # Integers

array([[8, 6, 6],
       [9, 1, 4]], dtype=int32)

In [74]:
# Random Choice
np.random.choice([10, 20, 30], size=5, p=[0.1, 0.3, 0.6])

array([10, 20, 30, 30, 30])

In [76]:
# Shuffle and Permutation
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.random.shuffle(a)         # In-place

In [83]:
a

array([2, 4, 5, 9, 7, 0, 8, 1, 3, 6])

In [84]:
np.random.permutation(a)     # Returns new array
a

array([2, 4, 5, 9, 7, 0, 8, 1, 3, 6])

In [85]:
# Setting seed for reproducibility
np.random.seed(42)

## 12. Normalize Rows of a Matrix

In [2]:
import numpy as np
def normalize_rows(x):
    return x / np.linalg.norm(x, axis=1, keepdims=True)

matrix = np.random.rand(3, 3)
normalized_matrix = normalize_rows(matrix)
print(normalized_matrix)

[[0.74055625 0.29745348 0.60257603]
 [0.6481751  0.51808152 0.55808653]
 [0.36914744 0.10253563 0.92369725]]


## 13. Custom Universal Function

In [3]:
# Define a custom function
def custom_func(x):
    return x**2 + 2*x + 1

#Vectorize the function
vectorized_func = np.vectorize(custom_func)

#Apply to array
arr = np.array([1, 2, 3])
print(vectorized_func(arr))
#Output: [4 9 16]

[ 4  9 16]


## 14. Memory Efficiency: Views vs. Copies

In [4]:
a = np.arange(10)
b = a[::2]  # This is a view
b[0] = 100
print(a)    # Output: [100   1   2   3   4   5   6   7   8   9]

[100   1   2   3   4   5   6   7   8   9]


## 16. Vectorization

In [5]:
# Loop
a = [1, 2, 3, 4]
b = [x**2 for x in a]

In [6]:
a

[1, 2, 3, 4]

In [7]:
b

[1, 4, 9, 16]

In [8]:
# Vectorization
import numpy as np
a = np.array([1, 2, 3, 4])
b = a ** 2  # Vectorized

In [9]:
a

array([1, 2, 3, 4])

In [10]:
b

array([ 1,  4,  9, 16])

In [11]:
%timeit [x**2 for x in range(100000)]        # Slower
%timeit np.arange(100000) ** 2               # Faster

12 ms ± 329 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
783 μs ± 30.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## 17. C-order vs Fortran-order   

In [12]:
a = np.array([[1, 2], [3, 4]], order='C')
a

array([[1, 2],
       [3, 4]])

In [13]:
b = np.array([[1, 2], [3, 4]], order='F')
b

array([[1, 2],
       [3, 4]])

In [14]:
# view(): Shares memory   
b = a.view()
b

array([[1, 2],
       [3, 4]])

In [15]:
# copy(): Independent data
c = a.copy()
c

array([[1, 2],
       [3, 4]])

## 18. Memory Info

In [16]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
# nbytes: Total bytes consumed     
print(a.nbytes)      # Total memory

32


In [18]:
# strides: Steps (in bytes) to move in each dimension
print(a.strides)     # e.g., (16, 8)

(16, 8)
